### ISSUE TITLE
`conda-forge` package

### ISSUE THREAD

**Issue by tasansal** [alexmojaki/eval_type_backport#12]
Hello, I have a project that I publish on `conda-forge` that has a dependency to this package.

Since `eval-type-backport` is not available on `conda`, we can't publish our package. 

Are there plans to make this available in `conda-forge`? It is a simple process: https://conda-forge.org/docs/maintainer/adding_pkgs/

I can also put it up there if you like.

**Comment by alexmojaki** [comment]
Please put it up there.

**Comment by tasansal** [comment]
@alexmojaki I created the recipe for `conda-forge` team's review. 

I also added you as a maintainer next to my name, if you can go there and say you are willing to be on the maintainers list that'd be great.

https://github.com/conda-forge/staged-recipes/pull/25689

Maintaining usually involves approving PRs from a bot when a new version is available on pip. And also if your dependencies (or their versions) change, you just update the `meta.yaml`.

Cheers

**Comment by tasansal** [comment]
It's live 🥳

https://anaconda.org/conda-forge/eval_type_backport

**Comment by tasansal** [comment]
@alexmojaki seems like I messed up the hyphen / underscore in the name. I'll resolve that soon.

**Comment by alexmojaki** [comment]
Thanks for taking care of this!
