### ISSUE TITLE
Optimize CI build matrix

### ISSUE THREAD

**Issue by johnslavik** [alexmojaki/eval_type_backport#16]
In Coherent OSS, I asked jaraco about [this very specific test matrix](https://github.com/jaraco/skeleton/blob/6ff02e0eefcd90e271cefd326b460ecfa0e3eb9e/.github/workflows/main.yml#L34-L50) in his CI setups, used widely in projects like setuptools or pip-run.

I made him write this doc: https://blog.jaraco.com/efficient-use-of-ci-resources/

A PR utilizing this practice is going to land soon.

**Comment by alexmojaki** [comment]
The matrix here is specifically meant to match that of pydantic. I don't want to change it. Also this repo is probably not going to get much activity so I don't think it's worth optimising it.

**Comment by johnslavik** [comment]
Alright, I'll go ahead and suggest that matrix to pydantic. Thanks!
